### ISSUE TITLE
Nefunguje příklad na knihovnu click

### ISSUE THREAD

**Issue by pilatcen** [cvut/MI-PYT#13]
Ahoj, čím by to mohlo být? Stará verze pythonu?

Jedná se o zkopírovaný příklad z eduxu/http://click.pocoo.org/5/

``` sh
(env)user@komp:~/Desktop/github-robot$ pip install click
Requirement already satisfied (use --upgrade to upgrade): click in ./env/lib/python3.4/site-packages
Cleaning up...

(env)user@komp:~/Desktop/github-robot$ python3 click.py --help
Traceback (most recent call last):
  File "click.py", line 1, in <module>
    import click
  File "/home/user/Desktop/github-robot/click.py", line 3, in <module>
    @click.command()
AttributeError: 'module' object has no attribute 'command'

(env)user@komp:~/Desktop/github-robot$ python3 click.py --count=3
Traceback (most recent call last):
  File "click.py", line 1, in <module>
    import click
  File "/home/user/Desktop/github-robot/click.py", line 3, in <module>
    @click.command()
AttributeError: 'module' object has no attribute 'command'
```

**Comment by slowbackspace** [comment]
Len tak strieľam, ale skúsil by som premenovať script z click.py na niečo iné.

**Comment by pilatcen** [comment]
Díky, bylo to tím. Tohle sem nečekal :)

**Comment by hroncok** [comment]
A víš, proč se to tak chová?

**Comment by slowbackspace** [comment]
`import click` chcel namiesto inštalovanej knižice importovať samotný script click.py. Pretože zrejme zložka z ktorej sa spúšťa script má prednosť?
Yup
https://docs.python.org/3.5/tutorial/modules.html#the-module-search-path

**Comment by hroncok** [comment]
To byla otázka na @pilatcen :)

Každopádně teď už to ví.
