### ISSUE TITLE
500 na python anywhere, ImportError: No module named 'robot.py'; 'robot' is not a package

### ISSUE THREAD

**Issue by pilatcen** [cvut/MI-PYT#21]
Ahoj,

zde http://pilatcen.pythonanywhere.com/ dostavam 500, hledal jsem google, ale moc jsem z toho moudry nebyl. Cim to muze byt?

/var/www/pilatcen_pythonanywhere_com_wsgi.py

``` py
import sys
path = '/home/pilatcen/1.HW-MI-PYT/'
if path not in sys.path:
    sys.path.append(path)
from robot.py import app as application
```

Python anywhere error log:

```
ImportError: No module named 'robot.py'; 'robot' is not a package
2016-10-15 19:45:32,911 :Error running WSGI application
Traceback (most recent call last):
  File "/bin/user_wsgi_wrapper.py", line 154, in __call__
    app_iterator = self.app(environ, start_response)
  File "/bin/user_wsgi_wrapper.py", line 170, in import_error_application
    raise e
  File "/bin/user_wsgi_wrapper.py", line 154, in __call__
    app_iterator = self.app(environ, start_response)
  File "/bin/user_wsgi_wrapper.py", line 170, in import_error_application
    raise e
  File "/bin/user_wsgi_wrapper.py", line 154, in __call__
    app_iterator = self.app(environ, start_response)
  File "/bin/user_wsgi_wrapper.py", line 170, in import_error_application
    raise e
  File "/bin/user_wsgi_wrapper.py", line 154, in __call__
    app_iterator = self.app(environ, start_response)
  File "/bin/user_wsgi_wrapper.py", line 170, in import_error_application
    raise e
  File "/bin/user_wsgi_wrapper.py", line 179, in <module>
    application = load_wsgi_application()
  File "/bin/user_wsgi_wrapper.py", line 175, in load_wsgi_application
    return __import__(os.environ['WSGI_MODULE'], globals(), locals(), ['application']).application
  File "/var/www/pilatcen_pythonanywhere_com_wsgi.py", line 6, in <module>
    from robot.py import app as application
ImportError: No module named 'robot.py'; 'robot' is not a package
```

**Comment by encukou** [comment]
Soubor `robot.py` obsahuje kód pro modul `robot`. Příkaz `import` chce jméno modulu, tedy bez toho `.py`.

**Comment by hroncok** [comment]
Zkus robot bez přípony.

**Comment by pilatcen** [comment]
Bez pripony dava http://pilatcen.pythonanywhere.com/ 404
Muzu na python anywhere nekde nastavit parametry prikazove radky, aby robot vedel kde ma konfig s pravidly?

**Comment by hroncok** [comment]
Ne, ale můžeš v `pilatcen_pythonanywhere_com_wsgi.py` nastavit něco do `application.config` slovníku a v aplikaci z něj číst.

**Comment by pilatcen** [comment]
Diky za odpoved.
Tu 404 mam asi vyresenou, v navodu na eduxu jsem nenasel, ze je treba nastavit Source code: v python anywhere (ale mozna jsem jen slepy a nevidim to)

**Comment by hroncok** [comment]
Teď přesně nevím, kde a co myslíš.

**Comment by hroncok** [comment]
Mám to takhle

![pa](https://cloud.githubusercontent.com/assets/2401856/19413148/f2fa17b4-9325-11e6-9a87-d80c15010bf0.png)

**Comment by pilatcen** [comment]
Tohle:
`
Code:
What your site is running.
Source code:
/home/pilatcen/1.HW-MI-PYT
`

**Comment by pilatcen** [comment]
aha, tak me to bez vyplneni hazelo tu 404

**Comment by hroncok** [comment]
Divný. Hlavně, jestli už to funguje.

**Comment by pilatcen** [comment]
Tak tim to nebylo.

Z konzole na vlastnim PC tu aplikaci pomoci python3 robot.py spustim, muzu na ni pristoupit na localhost:5000 a localhost:5000/hook

Na python anywhere spustim to, co jsme delali ve skole, ale uz ne svoji app. Na co bych se mel zamerit?

**Comment by hroncok** [comment]
Co říkají logy?

**Comment by pilatcen** [comment]
Nejspis to bude neco v kodu aplikace

Error log cisty

Access log
`185.47.222.228 - - [15/Oct/2016:21:00:14 +0000] "GET /hook HTTP/1.1" 404 233 "-" "Mozilla/5.0 (X11; Linux i686; rv:28.0) Gecko/20100101 Firefox/28.0" "185.47.222.228"`

server log
`2016-10-15 20:54:04 *** Starting uWSGI 2.0.5.1 (64bit) on [Sat Oct 15 20:54:03 2016] ***
2016-10-15 20:54:04 compiled with version: 4.8.4 on 29 September 2016 15:51:09
2016-10-15 20:54:04 os: Linux-3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016
2016-10-15 20:54:04 nodename: giles-liveweb4
2016-10-15 20:54:04 machine: x86_64
2016-10-15 20:54:04 clock source: unix
2016-10-15 20:54:04 pcre jit disabled
2016-10-15 20:54:04 detected number of CPU cores: 4
2016-10-15 20:54:04 current working directory: /etc/uwsgi/vassals
2016-10-15 20:54:04 detected binary path: /usr/local/bin/uwsgi
2016-10-15 20:54:04 *** dumping internal routing table ***
2016-10-15 20:54:04 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2016-10-15 20:54:04 *** end of the internal routing table ***
2016-10-15 20:54:04 using Linux cgroup /mnt/cgroups/cpu/user_types/free with mode 700
2016-10-15 20:54:04 assigned process 5235 to cgroup /mnt/cgroups/cpu/user_types/free/tasks
2016-10-15 20:54:04 using Linux cgroup /mnt/cgroups/cpuacct/domains/pilatcen.pythonanywhere.com with mode 700
2016-10-15 20:54:04 assigned process 5235 to cgroup /mnt/cgroups/cpuacct/domains/pilatcen.pythonanywhere.com/tasks
2016-10-15 20:54:04 using Linux cgroup /mnt/cgroups/memory/domains/pilatcen.pythonanywhere.com with mode 700
2016-10-15 20:54:04 assigned process 5235 to cgroup /mnt/cgroups/memory/domains/pilatcen.pythonanywhere.com/tasks
2016-10-15 20:54:04 uWSGI running as root, you can use --uid/--gid/--chroot options
2016-10-15 20:54:04 chroot() to /mnt/chroots/pilatcen/dangermouse
2016-10-15 20:54:04 setgid() to 60000
2016-10-15 20:54:04 setuid() to 1884628
2016-10-15 20:54:04 limiting number of processes to 15...
2016-10-15 20:54:04 your processes number limit is 15
2016-10-15 20:54:04 your memory page size is 4096 bytes
2016-10-15 20:54:04 detected max file descriptor number: 123456
2016-10-15 20:54:04 building mime-types dictionary from file /etc/mime.types...
2016-10-15 20:54:04 536 entry found
2016-10-15 20:54:04 lock engine: pthread robust mutexes
2016-10-15 20:54:04 thunder lock: disabled (you can enable it with --thunder-lock)
2016-10-15 20:54:04 uwsgi socket 0 bound to UNIX address /var/sockets/pilatcen.pythonanywhere.com/socket fd 7
2016-10-15 20:54:04 Python version: 3.5.2 (default, Jul 17 2016, 00:00:00)  [GCC 4.8.4]
2016-10-15 20:54:04 Set PythonHome to /home/pilatcen/env
2016-10-15 20:54:04 *** Python threads support is disabled. You can enable it with --enable-threads ***
2016-10-15 20:54:04 Python main interpreter initialized at 0x21c1280
2016-10-15 20:54:04 your server socket listen backlog is limited to 100 connections
2016-10-15 20:54:04 your mercy for graceful operations on workers is 60 seconds
2016-10-15 20:54:04 setting request body buffering size to 65536 bytes
2016-10-15 20:54:04 mapped 333952 bytes (326 KB) for 1 cores
2016-10-15 20:54:04 *** Operational MODE: single process ***
2016-10-15 20:54:04 initialized 35 metrics
2016-10-15 20:54:04 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x21c1280 pid: 5235 (default app)
2016-10-15 20:54:04 *** uWSGI is running in multiple interpreter mode ***
2016-10-15 20:54:04 spawned uWSGI master process (pid: 5235)
2016-10-15 20:54:04 spawned uWSGI worker 1 (pid: 5237, cores: 1)
2016-10-15 20:54:04 metrics collector thread started
2016-10-15 20:54:04 spawned 2 offload threads for uWSGI worker 1
2016-10-15 20:54:06 announcing my loyalty to the Emperor...`

**Comment by pilatcen** [comment]
Tak uz mi to funguje, ale az po te, co jsem nekolikrat dal reload app

**Comment by hroncok** [comment]
```
185.47.222.228 - - [15/Oct/2016:21:00:14 +0000] "GET /hook HTTP/1.1" 404 233 "-" "Mozilla/5.0 (X11; Linux i686; rv:28.0) Gecko/20100101 Firefox/28.0" "185.47.222.228"
```

To dává smysl vzhledem k:

```
@app.route('/hook', methods=['POST'])
```

/hook umí jen POST

**Comment by pilatcen** [comment]
Ok, thx

**Comment by jirutka** [comment]
@pilatcen Mohl by ses naučit, jak se v Markdown formátují _bloky_ kódu? Párkrát jsem to po tobě opravil, doufaje, že tě to trkne…

**Comment by pilatcen** [comment]
@jirutka opraveno
